Name: production-api
Host: 0.0.0.0
Port: 10003
Mode: dev

Log:
  ServiceName: production-api
  Level: info

DB:
  DataSource: root:root@tcp(127.0.0.1:3306)/trytry?charset=utf8mb4&parseTime=true&loc=UTC
Cache:
  - Host: 127.0.0.1:6379
    Pass: redispwd
    Type: node

OAuth:
  PublicKey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwyQ7CJm/Z07LIRsI+GBa
    fG5Fyx7PnvVpBsAyicXU6qWJGjbKQfIneOXFrXQmSg1jlbfYgb7uYpLqeJ49PpOZ
    llCgX1K87WdtIMT19c3ogbJAZl2mSGiUufSUpHx11GxXwyXCIrM4XQeAxNTlGxfh
    UV3uisskeHUqubMLVPxeKg5l9/fPKYXBq9iedqTkH3ZJ01x/THwicdcZpZs3qNZs
    51xjx4S0Xo+SjJX8LS+7LdGyobNNWJd7Jmq2oCwd0yvtkrpFtzItFR82FP3pyKrF
    ykFgWUwqsccC/Yd9MNRIvODdshtaFIxgXJ8YV89ZaslTKL3VjprueXYL8eSvPifi
    5QIDAQAB
    -----END PUBLIC KEY-----

OAuthRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: oauth.rpc