// Code generated by goctl. DO NOT EDIT.
package types

type HsptEstbReq struct {
	Name    string `json:"name"`
	Logo    string `json:"logo"`
	Welfare string `json:"welfare"`
	TsDate  int64  `json:"t_date"`
	TsTime  int64  `json:"t_time"`
}

type HsptEstbResp struct {
	Id      uint64 `json:"id"`
	Name    string `json:"name"`
	Logo    string `json:"logo"`
	Welfare string `json:"welfare"`
	TsDate  int64  `json:"t_date"`
	TsTime  int64  `json:"t_time"`
}

type HealthResp struct {
	Up string `json:"up"`
}
