// Code generated by goctl. DO NOT EDIT!
// Source: customer.proto

package server

import (
	"context"

	"github.com/v3nooonn/trytry/apps/customer/cmd/rpc/internal/logic"
	"github.com/v3nooonn/trytry/apps/customer/cmd/rpc/internal/svc"
	"github.com/v3nooonn/trytry/apps/customer/cmd/rpc/pb/customer"
)

type CustomerServer struct {
	svcCtx *svc.ServiceContext
	customer.UnimplementedCustomerServer
}

func NewCustomerServer(svcCtx *svc.ServiceContext) *CustomerServer {
	return &CustomerServer{
		svcCtx: svcCtx,
	}
}

func (s *CustomerServer) Info(ctx context.Context, in *customer.InfoReq) (*customer.InfoResp, error) {
	l := logic.NewInfoLogic(ctx, s.svcCtx)
	return l.Info(in)
}

func (s *CustomerServer) InfoByEmail(ctx context.Context, in *customer.InfoByEmailReq) (*customer.InfoResp, error) {
	l := logic.NewInfoByEmailLogic(ctx, s.svcCtx)
	return l.InfoByEmail(in)
}
