// Code generated by goctl. DO NOT EDIT.
// Source: production.proto

package server

import (
	"context"

	"github.com/v3nooonn/trytry/apps/production/internal/logic"
	"github.com/v3nooonn/trytry/apps/production/internal/svc"
	"github.com/v3nooonn/trytry/apps/production/pb/production"
)

type ProductionServiceServer struct {
	svcCtx *svc.ServiceContext
	production.UnimplementedProductionServiceServer
}

func NewProductionServiceServer(svcCtx *svc.ServiceContext) *ProductionServiceServer {
	return &ProductionServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductionServiceServer) Views(ctx context.Context, in *production.ViewsReq) (*production.ViewsResp, error) {
	l := logic.NewViewsLogic(ctx, s.svcCtx)
	return l.Views(in)
}

func (s *ProductionServiceServer) CarInfo(ctx context.Context, in *production.CarInfoReq) (*production.CarInfoResp, error) {
	l := logic.NewCarInfoLogic(ctx, s.svcCtx)
	return l.CarInfo(in)
}
