// Code generated by goctl. DO NOT EDIT.
// Source: organization.proto

package server

import (
	"context"

	"github.com/v3nooonn/trytry/apps/organization/internal/logic"
	"github.com/v3nooonn/trytry/apps/organization/internal/svc"
	"github.com/v3nooonn/trytry/apps/organization/pb/organization"
)

type OrganizationServer struct {
	svcCtx *svc.ServiceContext
	organization.UnimplementedOrganizationServer
}

func NewOrganizationServer(svcCtx *svc.ServiceContext) *OrganizationServer {
	return &OrganizationServer{
		svcCtx: svcCtx,
	}
}

func (s *OrganizationServer) Info(ctx context.Context, in *organization.InfoReq) (*organization.InfoResp, error) {
	l := logic.NewInfoLogic(ctx, s.svcCtx)
	return l.Info(in)
}
