// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productionBrandFieldNames          = builder.RawFieldNames(&ProductionBrand{})
	productionBrandRows                = strings.Join(productionBrandFieldNames, ",")
	productionBrandRowsExpectAutoSet   = strings.Join(stringx.Remove(productionBrandFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	productionBrandRowsWithPlaceHolder = strings.Join(stringx.Remove(productionBrandFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheTrytryProductionBrandIdPrefix = "cache:trytry:productionBrand:id:"
)

type (
	productionBrandModel interface {
		Insert(ctx context.Context, data *ProductionBrand) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ProductionBrand, error)
		Update(ctx context.Context, data *ProductionBrand) error
		Delete(ctx context.Context, id int64) error
	}

	defaultProductionBrandModel struct {
		sqlc.CachedConn
		table string
	}

	ProductionBrand struct {
		Id        int64     `db:"id"`
		Category  int64     `db:"category"`
		Name      string    `db:"name"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newProductionBrandModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultProductionBrandModel {
	return &defaultProductionBrandModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`production_brand`",
	}
}

func (m *defaultProductionBrandModel) Delete(ctx context.Context, id int64) error {
	trytryProductionBrandIdKey := fmt.Sprintf("%s%v", cacheTrytryProductionBrandIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, trytryProductionBrandIdKey)
	return err
}

func (m *defaultProductionBrandModel) FindOne(ctx context.Context, id int64) (*ProductionBrand, error) {
	trytryProductionBrandIdKey := fmt.Sprintf("%s%v", cacheTrytryProductionBrandIdPrefix, id)
	var resp ProductionBrand
	err := m.QueryRowCtx(ctx, &resp, trytryProductionBrandIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productionBrandRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductionBrandModel) Insert(ctx context.Context, data *ProductionBrand) (sql.Result, error) {
	trytryProductionBrandIdKey := fmt.Sprintf("%s%v", cacheTrytryProductionBrandIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, productionBrandRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Category, data.Name, data.CreatedAt, data.UpdatedAt)
	}, trytryProductionBrandIdKey)
	return ret, err
}

func (m *defaultProductionBrandModel) Update(ctx context.Context, data *ProductionBrand) error {
	trytryProductionBrandIdKey := fmt.Sprintf("%s%v", cacheTrytryProductionBrandIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productionBrandRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Category, data.Name, data.CreatedAt, data.UpdatedAt, data.Id)
	}, trytryProductionBrandIdKey)
	return err
}

func (m *defaultProductionBrandModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheTrytryProductionBrandIdPrefix, primary)
}

func (m *defaultProductionBrandModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productionBrandRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultProductionBrandModel) tableName() string {
	return m.table
}
