// Code generated by goctl. DO NOT EDIT.
// Source: brand.proto

package server

import (
	"context"

	"github.com/v3nooonn/trytry/apps/brand/internal/logic"
	"github.com/v3nooonn/trytry/apps/brand/internal/svc"
	"github.com/v3nooonn/trytry/apps/brand/pb/brand"
)

type BrandServer struct {
	svcCtx *svc.ServiceContext
	brand.UnimplementedBrandServer
}

func NewBrandServer(svcCtx *svc.ServiceContext) *BrandServer {
	return &BrandServer{
		svcCtx: svcCtx,
	}
}

func (s *BrandServer) Info(ctx context.Context, in *brand.InfoReq) (*brand.BrandInfo, error) {
	l := logic.NewInfoLogic(ctx, s.svcCtx)
	return l.Info(in)
}
