// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Brand struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Product struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Brand *Brand `json:"brand"`
}
