// Code generated by goctl. DO NOT EDIT!
// Source: oauth.proto

package server

import (
	"context"

	"github.com/v3nooonn/trytry-based-on-looklook/apps/oauth/cmd/rpc/internal/logic"
	"github.com/v3nooonn/trytry-based-on-looklook/apps/oauth/cmd/rpc/internal/svc"
	"github.com/v3nooonn/trytry-based-on-looklook/apps/oauth/cmd/rpc/pb/oauth"
)

type OauthServer struct {
	svcCtx *svc.ServiceContext
	oauth.UnimplementedOauthServer
}

func NewOauthServer(svcCtx *svc.ServiceContext) *OauthServer {
	return &OauthServer{
		svcCtx: svcCtx,
	}
}

func (s *OauthServer) Ping(ctx context.Context, in *oauth.Request) (*oauth.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
