gen-code:
	57ctl api go -api $(api_file) -dir ../ --remote="https://github.com/v3nooonn/trytry-template.git"
gen-def:
	57ctl api -o $(api_file) --remote="https://github.com/v3nooonn/trytry-template.git"
fmt:
	57ctl api format --dir .
