// Code generated by goctl. DO NOT EDIT.
package types

type Car struct {
	ID    uint64 `json:"id"`
	Brand string `json:"brand"`
	Serie string `json:"serie"`
}

type CarEstbReq struct {
	Brand uint64 `json:"brand"`
	Serie string `json:"serie"`
}

type CarEstbResp struct {
	Code    uint64 `json:"code"`
	Message string `json:"msg"`
	Data    Car    `json:"data"`
}

type CarInfoReq struct {
	ID uint64 `json:"id"`
}

type CarInfoResp struct {
	Code    uint64 `json:"code"`
	Message string `json:"msg"`
	Data    Car    `json:"data"`
}

type Brand struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
}

type BrandEstbReq struct {
	Brand string `json:"brand"`
}

type BrandEstbResp struct {
	Code    uint64 `json:"code"`
	Message string `json:"msg"`
	Data    Brand  `json:"data"`
}
