// Code generated by goctl. DO NOT EDIT.
package types

type URIID struct {
	ID int64 `json:"id"`
}

type PgnReq struct {
	Cursor int64 `form:"cursor"`
	Limit  int64 `form:"limit"`
}

type PgnResp struct {
	Prev string `json:"prev"`
	Next string `json:"next"`
}

type Pong struct {
	Up string `json:"up"`
}

type CustomerServiceResp struct {
	Up string `json:"up"`
}

type PageResp struct {
	Pagination  PgnResp      `json:"pagination"`
	Productions []Production `json:"data"`
}

type Production struct {
	ID           int64  `json:"id"`
	Brand        string `json:"brand"`
	Category     string `json:"category"`
	Series       string `json:"series"`
	Name         string `json:"name"`
	Abbreviation string `json:"abbreviation"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type InfoResp struct {
	ID           int64  `json:"id"`
	Brand        Brand  `json:"brand"`
	Category     string `json:"category"`
	Series       string `json:"series"`
	Name         string `json:"name"`
	Abbreviation string `json:"abbreviation"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type Brand struct {
	ID           int64        `json:"id"`
	Organization Organization `json:"organization"`
}

type Organization struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	Abbreviation string `json:"abbreviation"`
}
