// Code generated by goctl. DO NOT EDIT.
package types

type Pong struct {
	Up string `json:"up"`
}

type CustomerServiceResp struct {
	Up string `json:"up"`
}

type ProdViews struct {
}

type ProdDetail struct {
	Up string `json:"up"`
}
