Name: production.rpc
Log:
  ServiceName: production.rpc
  Level: error
  Encoding: plain
Mode: dev

ListenOn: 0.0.0.0:8200
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: production.rpc

#Redis:
#  Host: 127.0.0.1:6379
#  Pass: redispwd
#  Type: node

DB:
  DataSource: postgres://pgadmin:pgadmin@127.0.0.1:5434/trytry?sslmode=disable
Cache:
  - Host: 127.0.0.1:6379
    Pass: redispwd
    Type: node