// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	brandFieldNames          = builder.RawFieldNames(&Brand{})
	brandRows                = strings.Join(brandFieldNames, ",")
	brandRowsExpectAutoSet   = strings.Join(stringx.Remove(brandFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	brandRowsWithPlaceHolder = strings.Join(stringx.Remove(brandFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	brandModel interface {
		Insert(ctx context.Context, data *Brand) (sql.Result, error)
		Update(ctx context.Context, data *Brand) error
		FindOne(ctx context.Context, id int64) (*Brand, error)
		Delete(ctx context.Context, id int64) error
	}

	defaultBrandModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Brand struct {
		Id           int64     `db:"id"`
		OwnBy        int64     `db:"own_by"`
		CategoryId   int64     `db:"category_id"`
		Name         string    `db:"name"`
		Abbreviation string    `db:"abbreviation"`
		CreatedAt    time.Time `db:"created_at"`
		UpdatedAt    time.Time `db:"updated_at"`
	}
)

func newBrandModel(conn sqlx.SqlConn) *defaultBrandModel {
	return &defaultBrandModel{
		conn:  conn,
		table: "`brand`",
	}
}

func (m *defaultBrandModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBrandModel) FindOne(ctx context.Context, id int64) (*Brand, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", brandRows, m.table)
	var resp Brand
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBrandModel) Insert(ctx context.Context, data *Brand) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, brandRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OwnBy, data.CategoryId, data.Name, data.Abbreviation)
	return ret, err
}

func (m *defaultBrandModel) Update(ctx context.Context, data *Brand) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, brandRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OwnBy, data.CategoryId, data.Name, data.Abbreviation, data.Id)
	return err
}

func (m *defaultBrandModel) tableName() string {
	return m.table
}
