gen-code:
	57ctl api go -api ./def/bff.api -dir . --remote="https://github.com/v3nooonn/trytry-template.git"

gen-bff:
	57ctl api -o ./def/bff.api --remote="https://github.com/v3nooonn/trytry-template.git"

gen-api:
	57ctl api -o ./def/apis/$(api).api --remote="https://github.com/v3nooonn/trytry-template.git"

fmt:
	57ctl api format --dir .
