// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: pb/production.proto

package production

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ViewsReq) Reset() {
	*x = ViewsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_production_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewsReq) ProtoMessage() {}

func (x *ViewsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_production_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewsReq.ProtoReflect.Descriptor instead.
func (*ViewsReq) Descriptor() ([]byte, []int) {
	return file_pb_production_proto_rawDescGZIP(), []int{0}
}

type ViewsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProdViews []*ProdView `protobuf:"bytes,1,rep,name=prod_views,json=prodViews,proto3" json:"prod_views,omitempty"`
}

func (x *ViewsResp) Reset() {
	*x = ViewsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_production_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewsResp) ProtoMessage() {}

func (x *ViewsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_production_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewsResp.ProtoReflect.Descriptor instead.
func (*ViewsResp) Descriptor() ([]byte, []int) {
	return file_pb_production_proto_rawDescGZIP(), []int{1}
}

func (x *ViewsResp) GetProdViews() []*ProdView {
	if x != nil {
		return x.ProdViews
	}
	return nil
}

type ProdView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category  string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	CreatedAt int64  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int64  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *ProdView) Reset() {
	*x = ProdView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_production_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProdView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProdView) ProtoMessage() {}

func (x *ProdView) ProtoReflect() protoreflect.Message {
	mi := &file_pb_production_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProdView.ProtoReflect.Descriptor instead.
func (*ProdView) Descriptor() ([]byte, []int) {
	return file_pb_production_proto_rawDescGZIP(), []int{2}
}

func (x *ProdView) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProdView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProdView) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProdView) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ProdView) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CarInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarId int64 `protobuf:"varint,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
}

func (x *CarInfoReq) Reset() {
	*x = CarInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_production_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarInfoReq) ProtoMessage() {}

func (x *CarInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_production_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarInfoReq.ProtoReflect.Descriptor instead.
func (*CarInfoReq) Descriptor() ([]byte, []int) {
	return file_pb_production_proto_rawDescGZIP(), []int{3}
}

func (x *CarInfoReq) GetCarId() int64 {
	if x != nil {
		return x.CarId
	}
	return 0
}

type CarInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProdId    int64  `protobuf:"varint,1,opt,name=prod_id,json=prodId,proto3" json:"prod_id,omitempty"`
	Id        int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Category  string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Type      string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Series    string `protobuf:"bytes,5,opt,name=series,proto3" json:"series,omitempty"`
	Name      string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt int64  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int64  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *CarInfoResp) Reset() {
	*x = CarInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_production_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarInfoResp) ProtoMessage() {}

func (x *CarInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_production_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarInfoResp.ProtoReflect.Descriptor instead.
func (*CarInfoResp) Descriptor() ([]byte, []int) {
	return file_pb_production_proto_rawDescGZIP(), []int{4}
}

func (x *CarInfoResp) GetProdId() int64 {
	if x != nil {
		return x.ProdId
	}
	return 0
}

func (x *CarInfoResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CarInfoResp) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CarInfoResp) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CarInfoResp) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *CarInfoResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CarInfoResp) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CarInfoResp) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_pb_production_proto protoreflect.FileDescriptor

var file_pb_production_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x0a, 0x0a, 0x08, 0x56, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71, 0x22, 0x40, 0x0a,
	0x09, 0x56, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x64, 0x5f, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x64,
	0x56, 0x69, 0x65, 0x77, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x56, 0x69, 0x65, 0x77, 0x73, 0x22,
	0x88, 0x01, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x64, 0x56, 0x69, 0x65, 0x77, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x23, 0x0a, 0x0a, 0x43, 0x61,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x61, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x61, 0x72, 0x49, 0x64, 0x22,
	0xd0, 0x01, 0x0a, 0x0b, 0x43, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x17, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x70, 0x72, 0x6f, 0x64, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x32, 0x85, 0x01, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x56, 0x69, 0x65, 0x77,
	0x73, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56,
	0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a,
	0x0a, 0x07, 0x43, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43,
	0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pb_production_proto_rawDescOnce sync.Once
	file_pb_production_proto_rawDescData = file_pb_production_proto_rawDesc
)

func file_pb_production_proto_rawDescGZIP() []byte {
	file_pb_production_proto_rawDescOnce.Do(func() {
		file_pb_production_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_production_proto_rawDescData)
	})
	return file_pb_production_proto_rawDescData
}

var file_pb_production_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_production_proto_goTypes = []interface{}{
	(*ViewsReq)(nil),    // 0: production.ViewsReq
	(*ViewsResp)(nil),   // 1: production.ViewsResp
	(*ProdView)(nil),    // 2: production.ProdView
	(*CarInfoReq)(nil),  // 3: production.CarInfoReq
	(*CarInfoResp)(nil), // 4: production.CarInfoResp
}
var file_pb_production_proto_depIdxs = []int32{
	2, // 0: production.ViewsResp.prod_views:type_name -> production.ProdView
	0, // 1: production.ProductionService.Views:input_type -> production.ViewsReq
	3, // 2: production.ProductionService.CarInfo:input_type -> production.CarInfoReq
	1, // 3: production.ProductionService.Views:output_type -> production.ViewsResp
	4, // 4: production.ProductionService.CarInfo:output_type -> production.CarInfoResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_production_proto_init() }
func file_pb_production_proto_init() {
	if File_pb_production_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_production_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_production_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_production_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProdView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_production_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_production_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_production_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_production_proto_goTypes,
		DependencyIndexes: file_pb_production_proto_depIdxs,
		MessageInfos:      file_pb_production_proto_msgTypes,
	}.Build()
	File_pb_production_proto = out.File
	file_pb_production_proto_rawDesc = nil
	file_pb_production_proto_goTypes = nil
	file_pb_production_proto_depIdxs = nil
}
